name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for environment initialization
        run: sleep 5 

      - name: Debug environment variables
        run: printenv
  
      - name: Debug ARTIFACT_NAME
        run: echo "ARTIFACT_NAME is set to ${{ secrets.NEW_ARTIFACT }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.NEW_ARTIFACT }}
          path: .
