name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest
    environment: dev  # Reference the 'dev' environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Debug FILENAME
        run: echo "FILENAME is set to ${{ secrets.FILENAME }}"  # Correctly access the secret

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.FILENAME }}   # Correctly use the secret for the artifact name
          path: .                         # Path to upload all files
