name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Debug FILENAME
        env:
          FILENAME: ${{ env.FILENAME }}
        run: echo "FILENAME is set to $FILENAME"


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}   # Reference the environment variable for the artifact name
          path: .
