name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v4
       
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: .
         
