name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug new_artifact
        run: echo "new_artifact is set to ${{ env.NEW_ARTIFACT }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.new_artifact }}
          path: .
