name: create_artifact

on: [push]

jobs:
  create_artifact_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v2.0.0
       
      - name: upload artifact
        uses: actions/checkout@v1.0.0
        with:
          name: created_artifact
          path: ./${{ env.FILENAME }}
         
